docments for ImageDataLoaders.from_name_func
muellerzr/fastai-docment-sprint pull request #67
Opened 2022-02-20 02:28 UTC by hamelsmu

This is a super small PR, to see if I'm doing things right.  Once I get the hang of the rules, I can do more :)

cc: @muellerzr @jph00

2022-02-20 20:18 UTC, muellerzr requested changes
Looks pretty good for your first one! Made a few comments

2022-02-20 20:18 UTC, muellerzr commented on fastai/vision/data.py
> +                       **kwargs) -> DataLoaders:
```suggestion
    def from_name_func(cls,
                       path:(str, Path), # Set the default path to a directory that a `Learner` can use to save files like models
                       fnames:list, # A list of `os.Pathlike`'s to individual image files
                       label_func:callable, # A function that receives a string (the file name) and outputs a label
                       **kwargs
                   ) -> DataLoaders:
```
Formatting nit + typing

2022-02-21 01:17 UTC, hamelsmu commented
Thanks for making commit suggestions.  I ❤️ it when people do this.  Makes life so much easier

2022-02-21 01:32 UTC, warner-benjamin requested changes
Added a suggestion to fix formatting per the [style guide](https://github.com/muellerzr/fastai-docment-sprint/blob/master/docs_src/style-guide.md).

Otherwise looks good.

2022-02-21 01:32 UTC, warner-benjamin commented on fastai/vision/data.py
> +                   ) -> DataLoaders:
```suggestion
    def from_name_func(cls,
        path:(str, Path), # Set the default path to a directory that a `Learner` can use to save files like models
        fnames:list, # A list of `os.Pathlike`'s to individual image files
        label_func:callable, # A function that receives a string (the file name) and outputs a label
        **kwargs
    ) -> DataLoaders:
```

2022-02-23 03:22 UTC, warner-benjamin approved these changes
Looks good.

2022-02-25 00:58 UTC, merged