Add documents to Interpretation in 20_interpret
muellerzr/fastai-docment-sprint pull request #71
Opened 2022-02-20 06:37 UTC by edwinhung

Add documents to Interpretation class

2022-02-20 20:34 UTC, muellerzr requested changes
Small nits before Benjamin takes a look

2022-02-20 20:34 UTC, muellerzr commented on fastai/interpret.py
> +# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/nbs/20_interpret.ipynb (unless otherwise specified).
Run `nbdev_build_lib` from the basedir, don't specify `--fname`

2022-02-20 20:34 UTC, muellerzr commented on fastai/interpret.py
> +        learn, # Model to be interpreted
```suggestion
        learn:Learner,
```

2022-02-20 20:34 UTC, muellerzr commented on fastai/interpret.py
> +        dl:DataLoader, # `DataLoader` for the model
```suggestion
        dl:DataLoader, # `DataLoader` to run inference over
```

2022-02-20 20:34 UTC, muellerzr commented on fastai/interpret.py
> +        losses:TensorBase, # Losses calculated from the model
```suggestion
        losses:TensorBase, # Losses calculated from `dl`
```

2022-02-20 20:34 UTC, muellerzr commented on fastai/interpret.py
> +        ds_idx:int=1, # Index of `DataLoader` when dl is None
```suggestion
        ds_idx:int=1, # Index of `learn.dls` when `dl` is None
```

2022-02-20 20:34 UTC, muellerzr commented on fastai/interpret.py
> +        k:(int,[int]), # Number of losses to plot
```suggestion
        k:(int,list), # Number of losses to plot
```

2022-02-21 21:03 UTC, edwinhung commented
> Small nits before Benjamin takes a look

Thanks for the suggestions. I think they make sense, so I commit changes.

2022-02-23 02:51 UTC, warner-benjamin requested changes
A few small things to clean up. Otherwise looks good. Thanks.

2022-02-23 02:51 UTC, warner-benjamin commented on fastai/interpret.py
> +        act=None # Activation function for prediction
```suggestion
        act=None # Override default or set prediction activation function
```

2022-02-23 02:51 UTC, warner-benjamin commented on fastai/interpret.py
> +        items:bool=False # Whether to return input item for each loss
```suggestion
    def top_losses(self,
        k:(int,None)=None, # Return `k` losses, defaults to all
        largest:bool=True, # Sort losses by largest or smallest
        items:bool=False # Whether to return input items
```

2022-02-23 02:51 UTC, warner-benjamin commented on fastai/interpret.py
> +        idxs:(TensorBase,list), # Index of predictions and targets
We are using list for any list-like object
```suggestion
        idxs:list, # Indices of predictions and targets
```

2022-02-23 04:26 UTC, edwinhung commented
> A few small things to clean up. Otherwise looks good. Thanks.

Thank you for the suggestion. It looks simpler.

2022-02-25 00:55 UTC, muellerzr commented
Thanks!

2022-02-25 00:55 UTC, merged