add docments to 33_text.models.core notebook
muellerzr/fastai-docment-sprint pull request #73
Opened 2022-02-20 14:28 UTC by arampacha

closes #23

2022-02-20 20:39 UTC, muellerzr requested changes
Left some nits, great start!

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +from typing import List
```suggestion
```
We don't use typing

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +    arch:type, # Class defining language model architecture
```suggestion
    arch:callable, # Function or class that can generate a language model architecture
```

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +    ): store_attr('bptt,module,pad_idx,max_len')
```suggestion
    ): 
        store_attr('bptt,module,pad_idx,max_len')
```

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +    mask:Tensor, # Boolian mask as returned by sentence encoder
```suggestion
    mask:Tensor, # Boolean mask as returned by sentence encoder
```

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +) -> Tensor: # Concattenation of [last_hidden, max_pool, avg_pool]
```suggestion
) -> Tensor: # Concatenation of [last_hidden, max_pool, avg_pool]
```

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +        ps:List[float], # List of dropout probabilities
```suggestion
        dims:list, # List of hidden sizes for MLP as `int`s
        ps:list, # List of dropout probabilities as `float`s
```

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +    arch:type, # Class defining language model architecture
Same nit as earlier w/ `callable` type + string

2022-02-20 20:39 UTC, muellerzr commented on fastai/text/models/core.py
> +    ps:List[float]=None, # List of dropout probabilities for classifier head
Remove typing and format similar to previous suggestion

2022-02-22 05:10 UTC, marii-moe requested changes
Joined this one because another Reviewer was needed. Only one requested change

2022-02-24 08:13 UTC, marii-moe approved these changes
LGTM

2022-02-25 00:52 UTC, muellerzr commented on fastai/text/models/core.py
> +    arch:callable, # Function or class that can generate a language model architecture
```suggestion
    arch, # Function or class that can generate a language model architecture
```
After talking with Jeremy, let's get rid of this type hint. The docment says enough

2022-02-25 00:53 UTC, muellerzr commented on fastai/text/models/core.py
> +    arch:callable, # Function or class that can generate a language model architecture
```suggestion
    arch, # Function or class that can generate a language model architecture
```

2022-02-25 00:54 UTC, muellerzr approved these changes
One small change due to new information and we're good!

2022-02-25 23:04 UTC, arampacha commented
sorry for a bit of a mess, I've got a lot of distraction lately

2022-03-01 07:31 UTC, merged