docment `Callback` core (13_callback.core)
muellerzr/fastai-docment-sprint pull request #74
Opened 2022-02-20 20:03 UTC by Bharat123rox

Closes #34

2022-02-20 20:06 UTC, Bharat123rox commented
Would like you to review `FetchPredsCallback` and provide inputs, I made best guesses based on the actual code of `get_preds()` but I'm not 100% sure, so would love the inputs from maintainers

2022-02-21 00:40 UTC, warner-benjamin requested changes
Please update the docments to reflect the [style guide](https://github.com/muellerzr/fastai-docment-sprint/blob/master/docs_src/style-guide.md) formatting and rephrase the docment comments to be more concise.

I modified `GatherPredsCallback.__init__` to reflect those changes as a suggestion.

Also, could you add doc strings to the `GatherPredsCallback` and `FetchPredsCallback` methods which are missing doc strings?

2022-02-21 00:40 UTC, warner-benjamin commented on fastai/callback/core.py
> +    ):
Suggested changes to `GatherPredsCallback.__init__`
```suggestion
    def __init__(self,
        with_input:bool=False, # Whether to return inputs
        with_loss:bool=False, # Whether to return losses
        save_preds:Path=None, # Path to save predictions
        save_targs:Path=None, # Path to save targets
        with_preds:bool=True, # Whether to return predictions
        with_targs:bool=True, # Whether to return targets
        concat_dim:int=0, # Dimension to concatenate returned tensors
        pickle_protocol:int=2 # Pickle protocol used to save predictions and targets
    ):
```

2022-02-21 04:01 UTC, Bharat123rox commented
Apologies @warner-benjamin I had some problems with commit metadata earlier and had to force push to remove those

2022-02-22 05:47 UTC, marii-moe requested changes

2022-02-22 05:47 UTC, marii-moe commented on fastai/callback/core.py
> +        reorder:bool=True # Whether to sort prediction results
```suggestion
    def __init__(self,
        ds_idx:int=1, # Index of dataset, 0 for train, 1 for valid, used if `dl` is not present
        dl:DataLoader=None, # `DataLoader` used for fetching `Learner` predictions
        with_input:bool=False, # Whether to return inputs in `GatherPredsCallback`
        with_decoded:bool=False, # Whether to return predicted class
        cbs:list=None, # `Callback` list to add to the `Learner`
        reorder:bool=True # Whether to sort prediction results
```

2022-02-22 05:49 UTC, marii-moe commented on fastai/callback/core.py
> +        reorder:bool=True # Whether to sort prediction results
Added a few clarifications to the docs.

2022-02-22 09:35 UTC, marii-moe approved these changes
LGTM

2022-02-22 17:56 UTC, warner-benjamin approved these changes

2022-02-22 17:57 UTC, merged