add docment for _pytorch_doc
muellerzr/fastai-docment-sprint pull request #85
Opened 2022-02-24 21:24 UTC by feynlee

This fixes issue #55.

2022-02-25 01:19 UTC, muellerzr commented
@jph00 could you please review this? It's not the typing library, and honestly it does make sense somewhat. But would like to know your thoughts. Thanks! 😄

2022-03-07 04:44 UTC, tmabraham requested changes

2022-03-07 04:44 UTC, tmabraham commented on fastai/_pytorch_doc.py
> +) -> str :
```suggestion
) -> str:
```

2022-03-07 04:44 UTC, tmabraham commented on fastai/_pytorch_doc.py
> +    mod:ModuleType, # A pytorch module
```suggestion
    mod:ModuleType, # A PyTorch module
```

2022-03-07 04:44 UTC, tmabraham commented on fastai/_pytorch_doc.py
> +    "Get the web page name for a pytorch module"
```suggestion
    "Get the webpage name for a PyTorch module"
```

2022-03-07 04:44 UTC, tmabraham commented on fastai/_pytorch_doc.py
> +    name:str, # Name of a pytorch module, class or function
```suggestion
    name:str, # Name of a PyTorch module, class or function
```

2022-03-11 22:22 UTC, tmabraham reviewed
Just one very minor change, otherwise I'm good.

2022-03-11 22:22 UTC, tmabraham commented on fastai/_pytorch_doc.py
> +    name:str, # Name of a PyTorch module, class or function
```suggestion
    name:str # Name of a PyTorch module, class or function
```

2022-03-12 20:28 UTC, feynlee commented on fastai/_pytorch_doc.py
> +    name:str, # Name of a PyTorch module, class or function
updated.

2022-03-13 00:02 UTC, tmabraham approved these changes

2022-03-13 16:57 UTC, warner-benjamin approved these changes
LGTM

2022-03-13 16:57 UTC, merged