documents 08_vision.data: TransformBlocks for vision
muellerzr/fastai-docment-sprint pull request #88
Opened 2022-02-28 01:36 UTC by ChrisRichardMiles

The only issue is that I changed an argument from `cls` to `clss`.  The problem is that show_doc does not show the "cls" argument. You can see that in the _format_args function [here]https://github.com/fastai/nbdev/blob/master/nbdev/showdoc.py#L347. I know we aren't supposed to touch any code, but I'm not sure what to do here.

2022-02-28 05:00 UTC, warner-benjamin requested changes
> The only issue is that I changed an argument from `cls` to `clss`

Yeah, this is a nonstarter. As you can see from the CI output, it broke existing code. If there's a bug in nbdev, it'll need to be fixed there.

Try installing the latest nbdev with bugfixes from github
```
pip install git+https://github.com/fastai/nbdev -U
```
and see if that resolves the issue. Otherwise, mention it and this PR in the sprint-chat.

2022-03-02 01:05 UTC, muellerzr commented
@ChrisRichardMiles please change this back to `cls`. We'll be addressing the cls issue in nbdev

2022-03-11 00:08 UTC, warner-benjamin requested changes
Please add back the deleted doc cell. Also, don't check changes to other notebooks then the one you are working on.

Some suggestions for doc string improvements, replicate these to the notebook and resolve the issues mentioned above and it will be ready to merge.

2022-03-11 00:08 UTC, warner-benjamin commented on fastai/vision/data.py
> +):
```suggestion
def BBoxLblBlock(
    vocab:list=None, # Vocab labels for bounding boxes
    add_na:bool=True # Add NaN as a background class
):
```

2022-03-11 00:08 UTC, warner-benjamin commented on fastai/vision/data.py
> +):
```suggestion
def MaskBlock(
    codes:list=None # Vocab labels for segmentation masks
):
```

2022-03-11 06:20 UTC, marii-moe requested changes

2022-03-11 06:20 UTC, marii-moe commented on fastai/vision/data.py
> +):
```suggestion
def ImageBlock(cls:PILBase=PILImage):
```
Can just add that as a typehint instead.

2022-03-11 22:42 UTC, warner-benjamin commented
@ChrisRichardMiles the changes need to be added to the `08_vision.data.ipynb` notebook and the unchanged notebooks reverted.

2022-03-12 04:26 UTC, ChrisRichardMiles commented
> @ChrisRichardMiles the changes need to be added to the `08_vision.data.ipynb` notebook and the unchanged notebooks reverted.

Ok I will do it first thing in the morning. Thanks for the help

2022-03-12 19:45 UTC, ChrisRichardMiles commented
@warner-benjamin @marii-moe 
I have made the suggested changes and reverted the notebooks that should not have been touched. I still have an annoying local error message that I haven't been able to fix yet. I will fix it as soon as I can (hopefully tonight) and then I will request reviews.

2022-03-12 20:34 UTC, warner-benjamin approved these changes
@ChrisRichardMiles Assuming the"UserWarning: __floordiv__ is deprecated" is what you are referring to, it was already checked into the codebase, so you don't need to worry about it. There is an issue open for it #3588.

LGTM. Thanks!

2022-03-13 00:06 UTC, ChrisRichardMiles commented
> @ChrisRichardMiles Assuming the"UserWarning: __floordiv__ is deprecated" is what you are referring to, it was already checked into the codebase, so you don't need to worry about it. There is an issue open for it #3588.
> 
> 
> 
> LGTM. Thanks!

No, I actually meant an error that I also had in my last PR. But looking again, I realize I misread the file changes, because that part is highlighted in red, so it seems it was deleted. I am still confused to see it at all, but I guess everything is ok, so I'm going to request the review of @marii-moe

2022-03-13 05:15 UTC, marii-moe approved these changes
LGTM

2022-03-13 05:16 UTC, merged