Add docments to General API and Debugging sections of 06_data.block n…
muellerzr/fastai-docment-sprint pull request #90
Opened 2022-03-03 15:17 UTC by butchland

Add docments for the following sections
* General API
   - DataBlock
   - datasets
   - dataloaders
 * Debugging
   - summary

2022-03-06 10:56 UTC, butchland commented
@warner-benjamin @muellerzr any updates on when you plan review or merge?

2022-03-06 22:15 UTC, warner-benjamin requested changes
Left a few suggestions and corrections. If you could replicate the suggestions the rest of the doc strings, everything else looks good.

2022-03-06 22:15 UTC, warner-benjamin commented on fastai/data/block.py
> +    ):
`path` also has a sneaky feature where it sets the `Learner` path location too
```suggestion
    def dataloaders(self,
        source,  # The data source
        path:str='.', # Data source and default `Learner` path
        verbose:bool=False, # Show verbose messages
        **kwargs
    ):
```

2022-03-06 22:53 UTC, kevinbird15 requested changes
nothing too big, just a few formatting nits and a few return ideas

2022-03-06 22:53 UTC, kevinbird15 commented on fastai/data/block.py
> +def summary(self: DataBlock,
```suggestion
def summary(self:DataBlock,
```

2022-03-06 22:53 UTC, kevinbird15 commented on fastai/data/block.py
> +        source,  # The data source
```suggestion
        source, # The data source
```

2022-03-06 22:53 UTC, kevinbird15 commented on fastai/data/block.py
> +        item_tfms:list=None,  # List of `ItemTransform`s, applied on an item
```suggestion
        item_tfms:list=None, # List of `ItemTransform`s, applied on an item
```

2022-03-06 22:53 UTC, kevinbird15 commented on fastai/data/block.py
> +    ):
```suggestion
    ) -> Datasets:
```

2022-03-06 22:53 UTC, kevinbird15 commented on fastai/data/block.py
> +    ):
```suggestion
    ) -> DataLoaders:
```

2022-03-06 23:01 UTC, kevinbird15 commented on fastai/data/block.py
> +        dl_type:TfmdDL=None, # Specific class that inherits `TfmdDL`
```suggestion
        dl_type:TfmdDL=None, # Task-specific `TfmdDL`, defaults to `block`'s dl_type or `TfmdDL` if none specified
```
Not sure I like my version, but tried to convey the hierarchy of how dl_type is populated: `__init__.dl_type` > `block.dl_type` > `self.dl_type`

2022-03-08 17:52 UTC, warner-benjamin approved these changes
I think we can remove the if none specified, as its implied by the defaults. Otherwise looks good to me.

2022-03-08 17:52 UTC, warner-benjamin commented on fastai/data/block.py
> +        dl_type:TfmdDL=None, # Task specific `TfmdDL`, defaults to `TfmdDL` if none specified
```suggestion
        type_tfms:list=None, # One or more `Transform`s
        item_tfms:list=None, # `ItemTransform`s, applied on an item
        batch_tfms:list=None, # `Transform`s or `RandTransform`s, applied by batch
        dl_type:TfmdDL=None, # Task specific `TfmdDL`, defaults to `TfmdDL`
```

2022-03-08 17:52 UTC, warner-benjamin commented on fastai/data/block.py
> +        getters:list=None, # Getter functions applied to results of `get_items`
```suggestion
        blocks:list=None, # One or more `TransformBlock`s
        dl_type:TfmdDL=None, # Task specific `TfmdDL`, defaults to `block`'s dl_type or`TfmdDL`
        getters:list=None, # Getter functions applied to results of `get_items`
```

2022-03-08 17:52 UTC, warner-benjamin commented on nbs/06_data.block.ipynb
> +    "        getters:list=None, # Getter functions applied to results of `get_items`\n",
```suggestion
    "        blocks:list=None, # One or more `TransformBlock`s\n",
    "        dl_type:TfmdDL=None, # Task specific `TfmdDL`, defaults to `block`'s dl_type or`TfmdDL`\n",
    "        getters:list=None, # Getter functions applied to results of `get_items`\n",
```

2022-03-08 17:52 UTC, warner-benjamin commented on nbs/06_data.block.ipynb
> +    "        dl_type:TfmdDL=None, # Task specific `TfmdDL`, defaults to `TfmdDL` if none specified \n",
```suggestion
    "        type_tfms:list=None, # One or more `Transform`s\n",
    "        item_tfms:list=None, # `ItemTransform`s, applied on an item\n",
    "        batch_tfms:list=None, # `Transform`s or `RandTransform`s, applied by batch\n",
    "        dl_type:TfmdDL=None, # Task specific `TfmdDL`, defaults to `TfmdDL`\n",
```

2022-03-10 04:18 UTC, kevinbird15 approved these changes
Agreed with Benjamin's last if none specified point then I think this is ready to merge!

2022-03-10 23:57 UTC, merged