Add docment to Datasets
muellerzr/fastai-docment-sprint pull request #97
Opened 2022-03-04 19:03 UTC by malligaraj

Implement `Datasets` task in issue #8

2022-03-05 17:56 UTC, kevinbird15 requested changes
A few small changes, but overall looking really good

2022-03-05 17:56 UTC, kevinbird15 commented on fastai/data/core.py
> +        tls=None, # A `TfmdLists` object
```suggestion
        tls:TfmdLists=None, # If None, self.tls is generated from `items` and `tfms`
```

2022-03-05 17:56 UTC, kevinbird15 commented on fastai/data/core.py
> +        tfms=None, # List of `Transform`(s) or `Pipeline` to apply
```suggestion
        tfms:(list,Pipeline)=None, # List of `Transform`(s) or `Pipeline` to apply
```

2022-03-05 17:56 UTC, kevinbird15 commented on fastai/data/core.py
> +        tfms=None, # List of `Transform`(s) or `Pipeline` to apply
```suggestion
        tfms:list=None, # List of `Transform`(s) or `Pipeline` to apply
```

2022-03-05 17:56 UTC, kevinbird15 commented on fastai/data/core.py
> +        items=None, # List of items to create `Datasets`
```suggestion
        items:list=None, # List of items to create `Datasets`
```

2022-03-05 17:56 UTC, kevinbird15 commented on fastai/data/core.py
> +        items=None, # List of items to create `Datasets`
```suggestion
        items:list=None, # List of items to create `Datasets`
```

2022-03-09 08:35 UTC, marii-moe requested changes

2022-03-09 08:35 UTC, marii-moe commented on fastai/data/core.py
> +        dl_type=None, # Type of `DataLoader`
```suggestion
        dl_type=None, # Default type of `DataLoader` used when function `FilteredBase.dataloaders` is called. 
```
This kind of gives more of an idea on what dl_type affects.

2022-03-10 04:21 UTC, kevinbird15 approved these changes
Looks good to me

2022-03-11 04:57 UTC, marii-moe approved these changes
LGTM

2022-03-11 04:57 UTC, merged